#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlNhanSuBenhVien.LinqBiz
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBenhVien")]
	public partial class QlBenhVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBangChamCong(BangChamCong instance);
    partial void UpdateBangChamCong(BangChamCong instance);
    partial void DeleteBangChamCong(BangChamCong instance);
    partial void InsertNhomQuyen(NhomQuyen instance);
    partial void UpdateNhomQuyen(NhomQuyen instance);
    partial void DeleteNhomQuyen(NhomQuyen instance);
    partial void InsertBangChiTietChamCong(BangChiTietChamCong instance);
    partial void UpdateBangChiTietChamCong(BangChiTietChamCong instance);
    partial void DeleteBangChiTietChamCong(BangChiTietChamCong instance);
    partial void InsertBangChiTietPhanCongCaTruc(BangChiTietPhanCongCaTruc instance);
    partial void UpdateBangChiTietPhanCongCaTruc(BangChiTietPhanCongCaTruc instance);
    partial void DeleteBangChiTietPhanCongCaTruc(BangChiTietPhanCongCaTruc instance);
    partial void InsertBangLuong(BangLuong instance);
    partial void UpdateBangLuong(BangLuong instance);
    partial void DeleteBangLuong(BangLuong instance);
    partial void InsertBangPhanCongCaTruc(BangPhanCongCaTruc instance);
    partial void UpdateBangPhanCongCaTruc(BangPhanCongCaTruc instance);
    partial void DeleteBangPhanCongCaTruc(BangPhanCongCaTruc instance);
    partial void InsertChiTietNhomQuyen(ChiTietNhomQuyen instance);
    partial void UpdateChiTietNhomQuyen(ChiTietNhomQuyen instance);
    partial void DeleteChiTietNhomQuyen(ChiTietNhomQuyen instance);
    partial void InsertChucNang(ChucNang instance);
    partial void UpdateChucNang(ChucNang instance);
    partial void DeleteChucNang(ChucNang instance);
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertHoSoNhanVien(HoSoNhanVien instance);
    partial void UpdateHoSoNhanVien(HoSoNhanVien instance);
    partial void DeleteHoSoNhanVien(HoSoNhanVien instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    #endregion
		
		public QlBenhVienDataContext() : 
				base(global::QlNhanSuBenhVien.Properties.Settings.Default.QLBenhVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QlBenhVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QlBenhVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QlBenhVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QlBenhVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BangChamCong> BangChamCongs
		{
			get
			{
				return this.GetTable<BangChamCong>();
			}
		}
		
		public System.Data.Linq.Table<NhomQuyen> NhomQuyens
		{
			get
			{
				return this.GetTable<NhomQuyen>();
			}
		}
		
		public System.Data.Linq.Table<BangChiTietChamCong> BangChiTietChamCongs
		{
			get
			{
				return this.GetTable<BangChiTietChamCong>();
			}
		}
		
		public System.Data.Linq.Table<BangChiTietPhanCongCaTruc> BangChiTietPhanCongCaTrucs
		{
			get
			{
				return this.GetTable<BangChiTietPhanCongCaTruc>();
			}
		}
		
		public System.Data.Linq.Table<BangLuong> BangLuongs
		{
			get
			{
				return this.GetTable<BangLuong>();
			}
		}
		
		public System.Data.Linq.Table<BangPhanCongCaTruc> BangPhanCongCaTrucs
		{
			get
			{
				return this.GetTable<BangPhanCongCaTruc>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietNhomQuyen> ChiTietNhomQuyens
		{
			get
			{
				return this.GetTable<ChiTietNhomQuyen>();
			}
		}
		
		public System.Data.Linq.Table<ChucNang> ChucNangs
		{
			get
			{
				return this.GetTable<ChucNang>();
			}
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<HoSoNhanVien> HoSoNhanViens
		{
			get
			{
				return this.GetTable<HoSoNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangChamCong")]
	public partial class BangChamCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBCC;
		
		private int _Thang;
		
		private int _SoCong;
		
		private System.Nullable<int> _SoCongHuongBHXH;
		
		private EntitySet<BangChiTietChamCong> _BangChiTietChamCongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBCCChanging(int value);
    partial void OnMaBCCChanged();
    partial void OnThangChanging(int value);
    partial void OnThangChanged();
    partial void OnSoCongChanging(int value);
    partial void OnSoCongChanged();
    partial void OnSoCongHuongBHXHChanging(System.Nullable<int> value);
    partial void OnSoCongHuongBHXHChanged();
    #endregion
		
		public BangChamCong()
		{
			this._BangChiTietChamCongs = new EntitySet<BangChiTietChamCong>(new Action<BangChiTietChamCong>(this.attach_BangChiTietChamCongs), new Action<BangChiTietChamCong>(this.detach_BangChiTietChamCongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBCC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBCC
		{
			get
			{
				return this._MaBCC;
			}
			set
			{
				if ((this._MaBCC != value))
				{
					this.OnMaBCCChanging(value);
					this.SendPropertyChanging();
					this._MaBCC = value;
					this.SendPropertyChanged("MaBCC");
					this.OnMaBCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int NOT NULL")]
		public int Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this.OnThangChanging(value);
					this.SendPropertyChanging();
					this._Thang = value;
					this.SendPropertyChanged("Thang");
					this.OnThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCong", DbType="Int NOT NULL")]
		public int SoCong
		{
			get
			{
				return this._SoCong;
			}
			set
			{
				if ((this._SoCong != value))
				{
					this.OnSoCongChanging(value);
					this.SendPropertyChanging();
					this._SoCong = value;
					this.SendPropertyChanged("SoCong");
					this.OnSoCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCongHuongBHXH", DbType="Int")]
		public System.Nullable<int> SoCongHuongBHXH
		{
			get
			{
				return this._SoCongHuongBHXH;
			}
			set
			{
				if ((this._SoCongHuongBHXH != value))
				{
					this.OnSoCongHuongBHXHChanging(value);
					this.SendPropertyChanging();
					this._SoCongHuongBHXH = value;
					this.SendPropertyChanged("SoCongHuongBHXH");
					this.OnSoCongHuongBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangChamCong_BangChiTietChamCong", Storage="_BangChiTietChamCongs", ThisKey="MaBCC", OtherKey="MaBCC")]
		public EntitySet<BangChiTietChamCong> BangChiTietChamCongs
		{
			get
			{
				return this._BangChiTietChamCongs;
			}
			set
			{
				this._BangChiTietChamCongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangChiTietChamCongs(BangChiTietChamCong entity)
		{
			this.SendPropertyChanging();
			entity.BangChamCong = this;
		}
		
		private void detach_BangChiTietChamCongs(BangChiTietChamCong entity)
		{
			this.SendPropertyChanging();
			entity.BangChamCong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomQuyen")]
	public partial class NhomQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhomQuyen;
		
		private string _TenNhomQuyen;
		
		private string _GhiChu;
		
		private EntitySet<ChiTietNhomQuyen> _ChiTietNhomQuyens;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomQuyenChanging(int value);
    partial void OnMaNhomQuyenChanged();
    partial void OnTenNhomQuyenChanging(string value);
    partial void OnTenNhomQuyenChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public NhomQuyen()
		{
			this._ChiTietNhomQuyens = new EntitySet<ChiTietNhomQuyen>(new Action<ChiTietNhomQuyen>(this.attach_ChiTietNhomQuyens), new Action<ChiTietNhomQuyen>(this.detach_ChiTietNhomQuyens));
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomQuyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNhomQuyen
		{
			get
			{
				return this._MaNhomQuyen;
			}
			set
			{
				if ((this._MaNhomQuyen != value))
				{
					this.OnMaNhomQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaNhomQuyen = value;
					this.SendPropertyChanged("MaNhomQuyen");
					this.OnMaNhomQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhomQuyen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenNhomQuyen
		{
			get
			{
				return this._TenNhomQuyen;
			}
			set
			{
				if ((this._TenNhomQuyen != value))
				{
					this.OnTenNhomQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenNhomQuyen = value;
					this.SendPropertyChanged("TenNhomQuyen");
					this.OnTenNhomQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomQuyen_ChiTietNhomQuyen", Storage="_ChiTietNhomQuyens", ThisKey="MaNhomQuyen", OtherKey="MaNhomQuyen")]
		public EntitySet<ChiTietNhomQuyen> ChiTietNhomQuyens
		{
			get
			{
				return this._ChiTietNhomQuyens;
			}
			set
			{
				this._ChiTietNhomQuyens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomQuyen_NguoiDung", Storage="_NguoiDungs", ThisKey="MaNhomQuyen", OtherKey="MaNhomQuyen")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietNhomQuyens(ChiTietNhomQuyen entity)
		{
			this.SendPropertyChanging();
			entity.NhomQuyen = this;
		}
		
		private void detach_ChiTietNhomQuyens(ChiTietNhomQuyen entity)
		{
			this.SendPropertyChanging();
			entity.NhomQuyen = null;
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhomQuyen = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhomQuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangChiTietChamCong")]
	public partial class BangChiTietChamCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBCC;
		
		private int _MaNV;
		
		private EntityRef<BangChamCong> _BangChamCong;
		
		private EntityRef<HoSoNhanVien> _HoSoNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBCCChanging(int value);
    partial void OnMaBCCChanged();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    #endregion
		
		public BangChiTietChamCong()
		{
			this._BangChamCong = default(EntityRef<BangChamCong>);
			this._HoSoNhanVien = default(EntityRef<HoSoNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBCC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaBCC
		{
			get
			{
				return this._MaBCC;
			}
			set
			{
				if ((this._MaBCC != value))
				{
					if (this._BangChamCong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBCCChanging(value);
					this.SendPropertyChanging();
					this._MaBCC = value;
					this.SendPropertyChanged("MaBCC");
					this.OnMaBCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._HoSoNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangChamCong_BangChiTietChamCong", Storage="_BangChamCong", ThisKey="MaBCC", OtherKey="MaBCC", IsForeignKey=true)]
		public BangChamCong BangChamCong
		{
			get
			{
				return this._BangChamCong.Entity;
			}
			set
			{
				BangChamCong previousValue = this._BangChamCong.Entity;
				if (((previousValue != value) 
							|| (this._BangChamCong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangChamCong.Entity = null;
						previousValue.BangChiTietChamCongs.Remove(this);
					}
					this._BangChamCong.Entity = value;
					if ((value != null))
					{
						value.BangChiTietChamCongs.Add(this);
						this._MaBCC = value.MaBCC;
					}
					else
					{
						this._MaBCC = default(int);
					}
					this.SendPropertyChanged("BangChamCong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoNhanVien_BangChiTietChamCong", Storage="_HoSoNhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public HoSoNhanVien HoSoNhanVien
		{
			get
			{
				return this._HoSoNhanVien.Entity;
			}
			set
			{
				HoSoNhanVien previousValue = this._HoSoNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._HoSoNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoNhanVien.Entity = null;
						previousValue.BangChiTietChamCongs.Remove(this);
					}
					this._HoSoNhanVien.Entity = value;
					if ((value != null))
					{
						value.BangChiTietChamCongs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("HoSoNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangChiTietPhanCongCaTruc")]
	public partial class BangChiTietPhanCongCaTruc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBPCCT;
		
		private int _MaNV;
		
		private EntityRef<BangPhanCongCaTruc> _BangPhanCongCaTruc;
		
		private EntityRef<HoSoNhanVien> _HoSoNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBPCCTChanging(int value);
    partial void OnMaBPCCTChanged();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    #endregion
		
		public BangChiTietPhanCongCaTruc()
		{
			this._BangPhanCongCaTruc = default(EntityRef<BangPhanCongCaTruc>);
			this._HoSoNhanVien = default(EntityRef<HoSoNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBPCCT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaBPCCT
		{
			get
			{
				return this._MaBPCCT;
			}
			set
			{
				if ((this._MaBPCCT != value))
				{
					if (this._BangPhanCongCaTruc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBPCCTChanging(value);
					this.SendPropertyChanging();
					this._MaBPCCT = value;
					this.SendPropertyChanged("MaBPCCT");
					this.OnMaBPCCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._HoSoNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangPhanCongCaTruc_BangChiTietPhanCongCaTruc", Storage="_BangPhanCongCaTruc", ThisKey="MaBPCCT", OtherKey="MaBPCCT", IsForeignKey=true)]
		public BangPhanCongCaTruc BangPhanCongCaTruc
		{
			get
			{
				return this._BangPhanCongCaTruc.Entity;
			}
			set
			{
				BangPhanCongCaTruc previousValue = this._BangPhanCongCaTruc.Entity;
				if (((previousValue != value) 
							|| (this._BangPhanCongCaTruc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangPhanCongCaTruc.Entity = null;
						previousValue.BangChiTietPhanCongCaTrucs.Remove(this);
					}
					this._BangPhanCongCaTruc.Entity = value;
					if ((value != null))
					{
						value.BangChiTietPhanCongCaTrucs.Add(this);
						this._MaBPCCT = value.MaBPCCT;
					}
					else
					{
						this._MaBPCCT = default(int);
					}
					this.SendPropertyChanged("BangPhanCongCaTruc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoNhanVien_BangChiTietPhanCongCaTruc", Storage="_HoSoNhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public HoSoNhanVien HoSoNhanVien
		{
			get
			{
				return this._HoSoNhanVien.Entity;
			}
			set
			{
				HoSoNhanVien previousValue = this._HoSoNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._HoSoNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoNhanVien.Entity = null;
						previousValue.BangChiTietPhanCongCaTrucs.Remove(this);
					}
					this._HoSoNhanVien.Entity = value;
					if ((value != null))
					{
						value.BangChiTietPhanCongCaTrucs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("HoSoNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangLuong")]
	public partial class BangLuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBL;
		
		private double _HeSoCV;
		
		private System.Nullable<double> _HeSoLuong;
		
		private System.Nullable<double> _PhuCapThamNien;
		
		private System.Nullable<double> _CacKhoanDongGop;
		
		private System.Nullable<double> _TongLuong;
		
		private System.Nullable<double> _ThucLinh;
		
		private EntitySet<HoSoNhanVien> _HoSoNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBLChanging(int value);
    partial void OnMaBLChanged();
    partial void OnHeSoCVChanging(double value);
    partial void OnHeSoCVChanged();
    partial void OnHeSoLuongChanging(System.Nullable<double> value);
    partial void OnHeSoLuongChanged();
    partial void OnPhuCapThamNienChanging(System.Nullable<double> value);
    partial void OnPhuCapThamNienChanged();
    partial void OnCacKhoanDongGopChanging(System.Nullable<double> value);
    partial void OnCacKhoanDongGopChanged();
    partial void OnTongLuongChanging(System.Nullable<double> value);
    partial void OnTongLuongChanged();
    partial void OnThucLinhChanging(System.Nullable<double> value);
    partial void OnThucLinhChanged();
    #endregion
		
		public BangLuong()
		{
			this._HoSoNhanViens = new EntitySet<HoSoNhanVien>(new Action<HoSoNhanVien>(this.attach_HoSoNhanViens), new Action<HoSoNhanVien>(this.detach_HoSoNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					this.OnMaBLChanging(value);
					this.SendPropertyChanging();
					this._MaBL = value;
					this.SendPropertyChanged("MaBL");
					this.OnMaBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSoCV", DbType="Float NOT NULL")]
		public double HeSoCV
		{
			get
			{
				return this._HeSoCV;
			}
			set
			{
				if ((this._HeSoCV != value))
				{
					this.OnHeSoCVChanging(value);
					this.SendPropertyChanging();
					this._HeSoCV = value;
					this.SendPropertyChanged("HeSoCV");
					this.OnHeSoCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSoLuong", DbType="Float")]
		public System.Nullable<double> HeSoLuong
		{
			get
			{
				return this._HeSoLuong;
			}
			set
			{
				if ((this._HeSoLuong != value))
				{
					this.OnHeSoLuongChanging(value);
					this.SendPropertyChanging();
					this._HeSoLuong = value;
					this.SendPropertyChanged("HeSoLuong");
					this.OnHeSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuCapThamNien", DbType="Float")]
		public System.Nullable<double> PhuCapThamNien
		{
			get
			{
				return this._PhuCapThamNien;
			}
			set
			{
				if ((this._PhuCapThamNien != value))
				{
					this.OnPhuCapThamNienChanging(value);
					this.SendPropertyChanging();
					this._PhuCapThamNien = value;
					this.SendPropertyChanged("PhuCapThamNien");
					this.OnPhuCapThamNienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CacKhoanDongGop", DbType="Float")]
		public System.Nullable<double> CacKhoanDongGop
		{
			get
			{
				return this._CacKhoanDongGop;
			}
			set
			{
				if ((this._CacKhoanDongGop != value))
				{
					this.OnCacKhoanDongGopChanging(value);
					this.SendPropertyChanging();
					this._CacKhoanDongGop = value;
					this.SendPropertyChanged("CacKhoanDongGop");
					this.OnCacKhoanDongGopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongLuong", DbType="Float")]
		public System.Nullable<double> TongLuong
		{
			get
			{
				return this._TongLuong;
			}
			set
			{
				if ((this._TongLuong != value))
				{
					this.OnTongLuongChanging(value);
					this.SendPropertyChanging();
					this._TongLuong = value;
					this.SendPropertyChanged("TongLuong");
					this.OnTongLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThucLinh", DbType="Float")]
		public System.Nullable<double> ThucLinh
		{
			get
			{
				return this._ThucLinh;
			}
			set
			{
				if ((this._ThucLinh != value))
				{
					this.OnThucLinhChanging(value);
					this.SendPropertyChanging();
					this._ThucLinh = value;
					this.SendPropertyChanged("ThucLinh");
					this.OnThucLinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangLuong_HoSoNhanVien", Storage="_HoSoNhanViens", ThisKey="MaBL", OtherKey="MaBL")]
		public EntitySet<HoSoNhanVien> HoSoNhanViens
		{
			get
			{
				return this._HoSoNhanViens;
			}
			set
			{
				this._HoSoNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoNhanViens(HoSoNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.BangLuong = this;
		}
		
		private void detach_HoSoNhanViens(HoSoNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.BangLuong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangPhanCongCaTruc")]
	public partial class BangPhanCongCaTruc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBPCCT;
		
		private System.DateTime _Nam;
		
		private EntitySet<BangChiTietPhanCongCaTruc> _BangChiTietPhanCongCaTrucs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBPCCTChanging(int value);
    partial void OnMaBPCCTChanged();
    partial void OnNamChanging(System.DateTime value);
    partial void OnNamChanged();
    #endregion
		
		public BangPhanCongCaTruc()
		{
			this._BangChiTietPhanCongCaTrucs = new EntitySet<BangChiTietPhanCongCaTruc>(new Action<BangChiTietPhanCongCaTruc>(this.attach_BangChiTietPhanCongCaTrucs), new Action<BangChiTietPhanCongCaTruc>(this.detach_BangChiTietPhanCongCaTrucs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBPCCT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBPCCT
		{
			get
			{
				return this._MaBPCCT;
			}
			set
			{
				if ((this._MaBPCCT != value))
				{
					this.OnMaBPCCTChanging(value);
					this.SendPropertyChanging();
					this._MaBPCCT = value;
					this.SendPropertyChanged("MaBPCCT");
					this.OnMaBPCCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Date NOT NULL")]
		public System.DateTime Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangPhanCongCaTruc_BangChiTietPhanCongCaTruc", Storage="_BangChiTietPhanCongCaTrucs", ThisKey="MaBPCCT", OtherKey="MaBPCCT")]
		public EntitySet<BangChiTietPhanCongCaTruc> BangChiTietPhanCongCaTrucs
		{
			get
			{
				return this._BangChiTietPhanCongCaTrucs;
			}
			set
			{
				this._BangChiTietPhanCongCaTrucs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangChiTietPhanCongCaTrucs(BangChiTietPhanCongCaTruc entity)
		{
			this.SendPropertyChanging();
			entity.BangPhanCongCaTruc = this;
		}
		
		private void detach_BangChiTietPhanCongCaTrucs(BangChiTietPhanCongCaTruc entity)
		{
			this.SendPropertyChanging();
			entity.BangPhanCongCaTruc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietNhomQuyen")]
	public partial class ChiTietNhomQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhomQuyen;
		
		private int _MaChucNang;
		
		private EntityRef<NhomQuyen> _NhomQuyen;
		
		private EntityRef<ChucNang> _ChucNang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomQuyenChanging(int value);
    partial void OnMaNhomQuyenChanged();
    partial void OnMaChucNangChanging(int value);
    partial void OnMaChucNangChanged();
    #endregion
		
		public ChiTietNhomQuyen()
		{
			this._NhomQuyen = default(EntityRef<NhomQuyen>);
			this._ChucNang = default(EntityRef<ChucNang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomQuyen", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhomQuyen
		{
			get
			{
				return this._MaNhomQuyen;
			}
			set
			{
				if ((this._MaNhomQuyen != value))
				{
					if (this._NhomQuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaNhomQuyen = value;
					this.SendPropertyChanged("MaNhomQuyen");
					this.OnMaNhomQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucNang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaChucNang
		{
			get
			{
				return this._MaChucNang;
			}
			set
			{
				if ((this._MaChucNang != value))
				{
					if (this._ChucNang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChucNangChanging(value);
					this.SendPropertyChanging();
					this._MaChucNang = value;
					this.SendPropertyChanged("MaChucNang");
					this.OnMaChucNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomQuyen_ChiTietNhomQuyen", Storage="_NhomQuyen", ThisKey="MaNhomQuyen", OtherKey="MaNhomQuyen", IsForeignKey=true)]
		public NhomQuyen NhomQuyen
		{
			get
			{
				return this._NhomQuyen.Entity;
			}
			set
			{
				NhomQuyen previousValue = this._NhomQuyen.Entity;
				if (((previousValue != value) 
							|| (this._NhomQuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomQuyen.Entity = null;
						previousValue.ChiTietNhomQuyens.Remove(this);
					}
					this._NhomQuyen.Entity = value;
					if ((value != null))
					{
						value.ChiTietNhomQuyens.Add(this);
						this._MaNhomQuyen = value.MaNhomQuyen;
					}
					else
					{
						this._MaNhomQuyen = default(int);
					}
					this.SendPropertyChanged("NhomQuyen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucNang_ChiTietNhomQuyen", Storage="_ChucNang", ThisKey="MaChucNang", OtherKey="MaChucNang", IsForeignKey=true)]
		public ChucNang ChucNang
		{
			get
			{
				return this._ChucNang.Entity;
			}
			set
			{
				ChucNang previousValue = this._ChucNang.Entity;
				if (((previousValue != value) 
							|| (this._ChucNang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucNang.Entity = null;
						previousValue.ChiTietNhomQuyens.Remove(this);
					}
					this._ChucNang.Entity = value;
					if ((value != null))
					{
						value.ChiTietNhomQuyens.Add(this);
						this._MaChucNang = value.MaChucNang;
					}
					else
					{
						this._MaChucNang = default(int);
					}
					this.SendPropertyChanged("ChucNang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucNang")]
	public partial class ChucNang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChucNang;
		
		private string _TenChucNang;
		
		private string _TenHienThiTrongMenu;
		
		private string _GhiChu;
		
		private EntitySet<ChiTietNhomQuyen> _ChiTietNhomQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChucNangChanging(int value);
    partial void OnMaChucNangChanged();
    partial void OnTenChucNangChanging(string value);
    partial void OnTenChucNangChanged();
    partial void OnTenHienThiTrongMenuChanging(string value);
    partial void OnTenHienThiTrongMenuChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public ChucNang()
		{
			this._ChiTietNhomQuyens = new EntitySet<ChiTietNhomQuyen>(new Action<ChiTietNhomQuyen>(this.attach_ChiTietNhomQuyens), new Action<ChiTietNhomQuyen>(this.detach_ChiTietNhomQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucNang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChucNang
		{
			get
			{
				return this._MaChucNang;
			}
			set
			{
				if ((this._MaChucNang != value))
				{
					this.OnMaChucNangChanging(value);
					this.SendPropertyChanging();
					this._MaChucNang = value;
					this.SendPropertyChanged("MaChucNang");
					this.OnMaChucNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucNang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenChucNang
		{
			get
			{
				return this._TenChucNang;
			}
			set
			{
				if ((this._TenChucNang != value))
				{
					this.OnTenChucNangChanging(value);
					this.SendPropertyChanging();
					this._TenChucNang = value;
					this.SendPropertyChanged("TenChucNang");
					this.OnTenChucNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHienThiTrongMenu", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenHienThiTrongMenu
		{
			get
			{
				return this._TenHienThiTrongMenu;
			}
			set
			{
				if ((this._TenHienThiTrongMenu != value))
				{
					this.OnTenHienThiTrongMenuChanging(value);
					this.SendPropertyChanging();
					this._TenHienThiTrongMenu = value;
					this.SendPropertyChanged("TenHienThiTrongMenu");
					this.OnTenHienThiTrongMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucNang_ChiTietNhomQuyen", Storage="_ChiTietNhomQuyens", ThisKey="MaChucNang", OtherKey="MaChucNang")]
		public EntitySet<ChiTietNhomQuyen> ChiTietNhomQuyens
		{
			get
			{
				return this._ChiTietNhomQuyens;
			}
			set
			{
				this._ChiTietNhomQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietNhomQuyens(ChiTietNhomQuyen entity)
		{
			this.SendPropertyChanging();
			entity.ChucNang = this;
		}
		
		private void detach_ChiTietNhomQuyens(ChiTietNhomQuyen entity)
		{
			this.SendPropertyChanging();
			entity.ChucNang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCV;
		
		private string _TenCV;
		
		private double _HeSoCV;
		
		private EntitySet<HoSoNhanVien> _HoSoNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(int value);
    partial void OnMaCVChanged();
    partial void OnTenCVChanging(string value);
    partial void OnTenCVChanged();
    partial void OnHeSoCVChanging(double value);
    partial void OnHeSoCVChanged();
    #endregion
		
		public ChucVu()
		{
			this._HoSoNhanViens = new EntitySet<HoSoNhanVien>(new Action<HoSoNhanVien>(this.attach_HoSoNhanViens), new Action<HoSoNhanVien>(this.detach_HoSoNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenCV
		{
			get
			{
				return this._TenCV;
			}
			set
			{
				if ((this._TenCV != value))
				{
					this.OnTenCVChanging(value);
					this.SendPropertyChanging();
					this._TenCV = value;
					this.SendPropertyChanged("TenCV");
					this.OnTenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSoCV", DbType="Float NOT NULL")]
		public double HeSoCV
		{
			get
			{
				return this._HeSoCV;
			}
			set
			{
				if ((this._HeSoCV != value))
				{
					this.OnHeSoCVChanging(value);
					this.SendPropertyChanging();
					this._HeSoCV = value;
					this.SendPropertyChanged("HeSoCV");
					this.OnHeSoCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_HoSoNhanVien", Storage="_HoSoNhanViens", ThisKey="MaCV", OtherKey="MaCV")]
		public EntitySet<HoSoNhanVien> HoSoNhanViens
		{
			get
			{
				return this._HoSoNhanViens;
			}
			set
			{
				this._HoSoNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoNhanViens(HoSoNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_HoSoNhanViens(HoSoNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoSoNhanVien")]
	public partial class HoSoNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _GioiTinh;
		
		private string _QueQuan;
		
		private string _DiaChiHienTai;
		
		private string _TrinhDo;
		
		private System.Nullable<System.DateTime> _NgayVaoLam;
		
		private string _SoBHXH;
		
		private int _MaBL;
		
		private int _MaKhoa;
		
		private int _MaCV;
		
		private EntitySet<BangChiTietChamCong> _BangChiTietChamCongs;
		
		private EntitySet<BangChiTietPhanCongCaTruc> _BangChiTietPhanCongCaTrucs;
		
		private EntityRef<BangLuong> _BangLuong;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnDiaChiHienTaiChanging(string value);
    partial void OnDiaChiHienTaiChanged();
    partial void OnTrinhDoChanging(string value);
    partial void OnTrinhDoChanged();
    partial void OnNgayVaoLamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoLamChanged();
    partial void OnSoBHXHChanging(string value);
    partial void OnSoBHXHChanged();
    partial void OnMaBLChanging(int value);
    partial void OnMaBLChanged();
    partial void OnMaKhoaChanging(int value);
    partial void OnMaKhoaChanged();
    partial void OnMaCVChanging(int value);
    partial void OnMaCVChanged();
    #endregion
		
		public HoSoNhanVien()
		{
			this._BangChiTietChamCongs = new EntitySet<BangChiTietChamCong>(new Action<BangChiTietChamCong>(this.attach_BangChiTietChamCongs), new Action<BangChiTietChamCong>(this.detach_BangChiTietChamCongs));
			this._BangChiTietPhanCongCaTrucs = new EntitySet<BangChiTietPhanCongCaTruc>(new Action<BangChiTietPhanCongCaTruc>(this.attach_BangChiTietPhanCongCaTrucs), new Action<BangChiTietPhanCongCaTruc>(this.detach_BangChiTietPhanCongCaTrucs));
			this._BangLuong = default(EntityRef<BangLuong>);
			this._ChucVu = default(EntityRef<ChucVu>);
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(100)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiHienTai", DbType="NVarChar(100)")]
		public string DiaChiHienTai
		{
			get
			{
				return this._DiaChiHienTai;
			}
			set
			{
				if ((this._DiaChiHienTai != value))
				{
					this.OnDiaChiHienTaiChanging(value);
					this.SendPropertyChanging();
					this._DiaChiHienTai = value;
					this.SendPropertyChanged("DiaChiHienTai");
					this.OnDiaChiHienTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDo", DbType="NChar(20)")]
		public string TrinhDo
		{
			get
			{
				return this._TrinhDo;
			}
			set
			{
				if ((this._TrinhDo != value))
				{
					this.OnTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._TrinhDo = value;
					this.SendPropertyChanged("TrinhDo");
					this.OnTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoLam", DbType="Date")]
		public System.Nullable<System.DateTime> NgayVaoLam
		{
			get
			{
				return this._NgayVaoLam;
			}
			set
			{
				if ((this._NgayVaoLam != value))
				{
					this.OnNgayVaoLamChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoLam = value;
					this.SendPropertyChanged("NgayVaoLam");
					this.OnNgayVaoLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBHXH", DbType="NChar(10)")]
		public string SoBHXH
		{
			get
			{
				return this._SoBHXH;
			}
			set
			{
				if ((this._SoBHXH != value))
				{
					this.OnSoBHXHChanging(value);
					this.SendPropertyChanging();
					this._SoBHXH = value;
					this.SendPropertyChanged("SoBHXH");
					this.OnSoBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", DbType="Int NOT NULL")]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					if (this._BangLuong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBLChanging(value);
					this.SendPropertyChanging();
					this._MaBL = value;
					this.SendPropertyChanged("MaBL");
					this.OnMaBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="Int NOT NULL")]
		public int MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="Int NOT NULL")]
		public int MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoNhanVien_BangChiTietChamCong", Storage="_BangChiTietChamCongs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<BangChiTietChamCong> BangChiTietChamCongs
		{
			get
			{
				return this._BangChiTietChamCongs;
			}
			set
			{
				this._BangChiTietChamCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoNhanVien_BangChiTietPhanCongCaTruc", Storage="_BangChiTietPhanCongCaTrucs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<BangChiTietPhanCongCaTruc> BangChiTietPhanCongCaTrucs
		{
			get
			{
				return this._BangChiTietPhanCongCaTrucs;
			}
			set
			{
				this._BangChiTietPhanCongCaTrucs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangLuong_HoSoNhanVien", Storage="_BangLuong", ThisKey="MaBL", OtherKey="MaBL", IsForeignKey=true)]
		public BangLuong BangLuong
		{
			get
			{
				return this._BangLuong.Entity;
			}
			set
			{
				BangLuong previousValue = this._BangLuong.Entity;
				if (((previousValue != value) 
							|| (this._BangLuong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangLuong.Entity = null;
						previousValue.HoSoNhanViens.Remove(this);
					}
					this._BangLuong.Entity = value;
					if ((value != null))
					{
						value.HoSoNhanViens.Add(this);
						this._MaBL = value.MaBL;
					}
					else
					{
						this._MaBL = default(int);
					}
					this.SendPropertyChanged("BangLuong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_HoSoNhanVien", Storage="_ChucVu", ThisKey="MaCV", OtherKey="MaCV", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.HoSoNhanViens.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.HoSoNhanViens.Add(this);
						this._MaCV = value.MaCV;
					}
					else
					{
						this._MaCV = default(int);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_HoSoNhanVien", Storage="_Khoa", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.HoSoNhanViens.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.HoSoNhanViens.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(int);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangChiTietChamCongs(BangChiTietChamCong entity)
		{
			this.SendPropertyChanging();
			entity.HoSoNhanVien = this;
		}
		
		private void detach_BangChiTietChamCongs(BangChiTietChamCong entity)
		{
			this.SendPropertyChanging();
			entity.HoSoNhanVien = null;
		}
		
		private void attach_BangChiTietPhanCongCaTrucs(BangChiTietPhanCongCaTruc entity)
		{
			this.SendPropertyChanging();
			entity.HoSoNhanVien = this;
		}
		
		private void detach_BangChiTietPhanCongCaTrucs(BangChiTietPhanCongCaTruc entity)
		{
			this.SendPropertyChanging();
			entity.HoSoNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhoa;
		
		private string _TenKhoa;
		
		private EntitySet<HoSoNhanVien> _HoSoNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaChanging(int value);
    partial void OnMaKhoaChanged();
    partial void OnTenKhoaChanging(string value);
    partial void OnTenKhoaChanged();
    #endregion
		
		public Khoa()
		{
			this._HoSoNhanViens = new EntitySet<HoSoNhanVien>(new Action<HoSoNhanVien>(this.attach_HoSoNhanViens), new Action<HoSoNhanVien>(this.detach_HoSoNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this.OnTenKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenKhoa = value;
					this.SendPropertyChanged("TenKhoa");
					this.OnTenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_HoSoNhanVien", Storage="_HoSoNhanViens", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<HoSoNhanVien> HoSoNhanViens
		{
			get
			{
				return this._HoSoNhanViens;
			}
			set
			{
				this._HoSoNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoNhanViens(HoSoNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_HoSoNhanViens(HoSoNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _MaNhomQuyen;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _TenTaiKhoan;
		
		private string _Email;
		
		private bool _TrangThai;
		
		private System.Nullable<System.DateTime> _ThoiGianDangNhapGanNhat;
		
		private EntityRef<NhomQuyen> _NhomQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaNhomQuyenChanging(int value);
    partial void OnMaNhomQuyenChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTrangThaiChanging(bool value);
    partial void OnTrangThaiChanged();
    partial void OnThoiGianDangNhapGanNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianDangNhapGanNhatChanged();
    #endregion
		
		public NguoiDung()
		{
			this._NhomQuyen = default(EntityRef<NhomQuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomQuyen", DbType="Int NOT NULL")]
		public int MaNhomQuyen
		{
			get
			{
				return this._MaNhomQuyen;
			}
			set
			{
				if ((this._MaNhomQuyen != value))
				{
					if (this._NhomQuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaNhomQuyen = value;
					this.SendPropertyChanged("MaNhomQuyen");
					this.OnMaNhomQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit NOT NULL")]
		public bool TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangNhapGanNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangNhapGanNhat
		{
			get
			{
				return this._ThoiGianDangNhapGanNhat;
			}
			set
			{
				if ((this._ThoiGianDangNhapGanNhat != value))
				{
					this.OnThoiGianDangNhapGanNhatChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianDangNhapGanNhat = value;
					this.SendPropertyChanged("ThoiGianDangNhapGanNhat");
					this.OnThoiGianDangNhapGanNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomQuyen_NguoiDung", Storage="_NhomQuyen", ThisKey="MaNhomQuyen", OtherKey="MaNhomQuyen", IsForeignKey=true)]
		public NhomQuyen NhomQuyen
		{
			get
			{
				return this._NhomQuyen.Entity;
			}
			set
			{
				NhomQuyen previousValue = this._NhomQuyen.Entity;
				if (((previousValue != value) 
							|| (this._NhomQuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomQuyen.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._NhomQuyen.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaNhomQuyen = value.MaNhomQuyen;
					}
					else
					{
						this._MaNhomQuyen = default(int);
					}
					this.SendPropertyChanged("NhomQuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
